export const pollsTxt = 'polls'
export const myPollsTxt = 'users_polls'
export const respondedPollsTxt = 'user_responded_polls'
export const tabClass = 'tablinks'
export const tabActiveClass = 'tablinks active'
export const FETCH_POLLS = 'FETCH_POLLS'
export const FETCH_USER_POLLS = 'FETCH_USER_POLLS'
export const FETCH_RESPONDED_POLLS = 'FETCH_RESPONDED_POLLS'