export const pollsTxt = 'polls'
export const myPollsTxt = 'users_polls'
export const respondedPollsTxt = 'user_responded_polls'
export const tabClass = 'tablinks'
export const tabActiveClass = 'tablinks active'